events{
  # 동시에 처리하는 연결 수
  worker_connections 1024;
}

server {
    listen 80;
    server_name a.com;
    return 301 https://$host$request_uri; # HTTP -> HTTPS 리다이렉트
}

server {
    listen 443 ssl;
    server_name a.com;

    ssl_certificate /etc/ssl/certs/a.com.crt;
    ssl_certificate_key /etc/ssl/private/a.com.key;

    location / {
        proxy_pass http://web-container:8000; # Hello 웹페이지
    }
}

server {
    listen 443 ssl;
    server_name b.a.com;

    ssl_certificate /etc/ssl/certs/a.com.crt;
    ssl_certificate_key /etc/ssl/private/a.com.key;

    location /product/display {
        proxy_pass http://api-container:8000/product/display;
    }
}

server {
    listen 443 ssl;
    server_name admin.a.com;

    ssl_certificate /etc/ssl/certs/a.com.crt;
    ssl_certificate_key /etc/ssl/private/a.com.key;

    allow 192.168.0.1; # 특정 IP 주소 허용
    deny all;

    location / {
        proxy_pass http://admin-container:8000; # Hello Admin 웹페이지
    }
}
